### PR TITLE
Date functions

### PR DESCRIPTION
**Pull request by HaydenMacDonald**
Hi there!

I've written two functions, `str_extract_before_date` and `str_extract_after_date`, to help users parse through URLs or file names that contain date patterns. Both take `symbol` and `format` as arguments to indicate what separators and format the date has, respectively. I've also written documentation and tests for both. 

I've also used `devtools::document()` to generate a new NAMESPACE file and included `glue` in the DESCRIPTION file. 

Let me know what you think! I'm very willing to make additional changes to suit the style or address any concerns. Cheers!

### CODE REVIEW

**Comment by johncassil** [comment]
Hayden,

First of all, thanks for this contribution.  I can see it being beneficial for finding text in strings before or after dates (without knowing what specific date you are looking for.)  

A couple questions (Apologies if I overlooked anything):
- I haven't played around with this year, but I'm slightly confused how the "symbol" function behaves.  Is there perhaps an opportunity to use lubridate's functions like mdy() to abstract this away from the end user?  May not be possible for all use cases, just wondering if you'd given it thought.
- When we include this, can you update it so that we are on: Version: 0.1.1  ?
- I think I'm fine with adding glue as a dependency for now.  That may be helpful in other areas.
- functions.R has grown quite a bit from my initial plans, and I think it might be time to split each function or group of functions into their own files for ease of reference and update.  Do you know how to do this?  Don't feel like you need to.  I don't want to put a lot of work on you, but if you can, that would perhaps be helpful and set the package up for success with future functions as well.

Let me know what you think!
JP

**Comment by HaydenMacDonald** [comment]
Hi John,

1. My thought process was that user's will have URL or file name strings with various separating symbols in and around the dates. For example, `file_name_2020_08_02.csv`, `url.com/index/2020-08-20.html`, `url.com/2020/08/20/index.html` or even no separator `filename20200802.csv`. When the user inputs the separator symbol, that symbol is included in the regex pattern for parsing the string (or leaves it as an empty string when there is no separator). Of course, this relies on the strings having consistent style. Unfortunately, using `lubridate`'s functions like `mdy()` and `ymd()` require the date to be relatively isolated, as they have trouble finding dates with characters on either side of the pattern. In the case of `str_extract_before_date` and `str_extract_after_date`, we need to parse through the full string for a date-like pattern before extracting the desired parts. In the end, it seemed easiest to create these custom regex patterns to recognize the most common date formats.
2. Yes, I can add the `v0.1.1` tag to the final commit in this request.
3. Great!
4. Yes. All you have to do is simply copy and paste the functions into a new .R file. I can help with this as well.

I can add some commits later today if this sounds good to you!

**Comment by johncassil** [comment]
Hayden,

Perfect! The explanation makes sense too... that's what my gut was telling me.

Just about ready to merge this, but one last question:

What do you think of renaming the "symbol" argument to something like "sep", "date_sep" or "date_part_sep"? I'm just thinking that other functions I tend to use frequently in R have a similar argument of "sep" for separator or 'delim' in certain cases.

Examples:

paste0(sep = " ") 
readr::read_delim(delim)
data.table::fread(sep)
tidyr::pivot_longer(names_sep = NULL)
tidyr::unnest(names_sep = NULL)

I think my preference would be to follow the tidyr standard (if you can call it that) and go with date_sep, but curious if you have thoughts since this is your function.

**Comment by johncassil** [comment]
Also, after we merge this in, it would be great to add a separate pull request to put an example or two in the readme. (I'm using that as the de facto vignette / intro to the package right now)

**Comment by HaydenMacDonald** [comment]
Yes, I'm certainly open to renaming `symbol` to `date_sep` for consistency. Also, if you'd like I can add those READMEs examples in this same pull request, unless you would prefer them in a separate pull request?

**Comment by johncassil** [comment]
One pull request is good!  :D

**Comment by HaydenMacDonald** [comment]
Hi John,

I believe I've made all of the requested changes as of the last commit of this pull request. Just to review, I've 

-  Tagged the last commit as "v0.1.1"
- Separated the functions into four separate R files by category
- Renamed the `symbol` argument to `date_sep`
- Added examples for `str_extract_before_date` and `str_extract_after_date` to both READMEs

Let me know if you have any other thoughts/comments.

**Pull request merged**
