### PR TITLE
Add function str_extract_context

### LINKED ISSUE #4: New function idea: str_context
Hi there,

A while back I wrote a function to return a window of a given size around a pattern. This is helpful for understanding the context of a detected string (e.g. how is this string used in my data, especially for very long blocks of text) as well as detecting false positives. 

For example:
`str_context(string = "In a hole in the ground there lived a hobbit.", pattern = "ground", window_size = 6)`
would return `"...n the ground there..."`

There would also be a parameter for how many matches to return.

Does this sound like an interesting/useful function for your package? If so I'd be happy to submit as a Hacktoberfest PR. Thanks!

### PR DESCRIPTION
**Pull request by abidawson**
Closes #4 

Hi again! Let me know what you think and if you want me to change anything. The new function isn't vectorized over `string`, which I'd like it to be eventually, but didn't think I'd be able to get there in the short term, and it looked like some of your other functions weren't either, so it seemed ok for consistency. 

Sorry that adding the test came through as a total replacement of the file, I'm not sure why that happened - in reality I just added a few lines (one test). 

Thanks!

### CODE REVIEW

**Comment by johncassil** [comment]
Hello, Abi,

As for vectorization, I've done a lot on this today, and I vectorized this too.  The "issue" is that we need to find a good way to collapse multiple return strings from one given string/pattern so they fit in with the tidy framework.

I came up with a way to vectorize it over string, pattern, and window size where the return (if there are multiple strings) would collapse them into one string separated by an ellipse: '...'

How do you like that idea?  Does it work for your use cases?

```
tibble::tribble(
    ~text, ~keyword, ~needed_context,
    "This is my first test string.", "first", 5,
    "This is a second one.", "second", 5,
    "This beef is incredible. I like all beef, but Angus beef is the best", "beef", 4,
    "I'm trying to become a vegetarian, though!", "vegetarian", 10 ) %>% 
    mutate(context = str_extract_context(text, keyword, needed_context)) %>%
    View()
```
image

**Comment by abidawson** [comment]
Hi John - I think this works and would definitely satisfy my use case. Thanks for taking it on. 

The argument I can think of for doing something different would be this - if you want to closely mimic the behavior of the functions in stringr, then I think we would want this function to perform similarly to `str_extract_all` in terms of output (with the addition of the context). The vectorization is handled differently there and gives a less "tidy" output of a list of vectors, one vector for each input string. 

For example:
```
text <- c("This is my first test string about beef.","This is a second one.","This beef is incredible. I like all beef, but Angus beef is the best")
stringr::str_extract_all(text,pattern = "beef")

[[1]]
[1] "beef"

[[2]]
character(0)

[[3]]
[1] "beef" "beef" "beef"
```

You could argue that although it requires more wrangling from the user, it also gives them more options (e.g. if they don't want them pasted together with ellipses). 

I'm 100% good with your solution, just wanted to throw this out there to see what you think. Thanks!

**Comment by johncassil** [comment]
Great point.  I think I would like it to match the behaviour from stringr.  I'll think about that and maybe redo it, or create str_extract_context() and str_extract_context_all() to match the api

**Comment by johncassil** [comment]
Should be updated as of https://github.com/johncassil/stringr.plus/pull/12 

Please re-install and check out the functions.  They should mirror stringr syntax pretty well now. 

window_size can be a static number across string and pattern, or can be vectorized as well.

**Pull request merged**
